table Date

	column date_key
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: date_key

	column date
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: date

	column year
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: year

	column quarter
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: quarter

	column quarter_label
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: quarter_label

	column year_quarter
		dataType: string
		summarizeBy: none
		sourceColumn: year_quarter

	column month
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: month

	column month_name
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: month_name

	column month_short
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: month_short

	column year_month
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: year_month

	column month_start
		dataType: dateTime
		formatString: mmm yy
		summarizeBy: none
		sourceColumn: month_start

	column month_end
		dataType: dateTime
		formatString: Short Date
		isHidden
		summarizeBy: none
		sourceColumn: month_end

	column week_start
		dataType: dateTime
		formatString: d mmm yy
		summarizeBy: none
		sourceColumn: week_start

	column iso_week
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: iso_week

	column day_of_month
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: day_of_month

	column day_of_week
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: day_of_week

	column day_name
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: day_name

	column is_weekend
		dataType: boolean
		isHidden
		summarizeBy: none
		sourceColumn: is_weekend

	column is_month_end
		dataType: boolean
		isHidden
		summarizeBy: none
		sourceColumn: is_month_end

	column days_in_month
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: days_in_month

	column fiscal_year
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: fiscal_year

	column fiscal_quarter
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: fiscal_quarter

	column is_in_analysis_period
		dataType: boolean
		isHidden
		summarizeBy: none
		sourceColumn: is_in_analysis_period

	column months_before_analysis_end
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: months_before_analysis_end

	partition Date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "dim_date.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    #"Typed columns" = Table.TransformColumnTypes(
				        #"Promoted headers",
				        {
						{"date_key", Int64.Type},
						{"date", type date},
						{"year", Int64.Type},
						{"quarter", Int64.Type},
						{"quarter_label", type text},
						{"year_quarter", type text},
						{"month", Int64.Type},
						{"month_name", type text},
						{"month_short", type text},
						{"year_month", type text},
						{"month_start", type date},
						{"month_end", type date},
						{"week_start", type date},
						{"iso_week", Int64.Type},
						{"day_of_month", Int64.Type},
						{"day_of_week", Int64.Type},
						{"day_name", type text},
						{"is_weekend", type logical},
						{"is_month_end", type logical},
						{"days_in_month", Int64.Type},
						{"fiscal_year", Int64.Type},
						{"fiscal_quarter", Int64.Type},
						{"is_in_analysis_period", type logical},
						{"months_before_analysis_end", Int64.Type}
				        },
				        "en-US"
				    )
				in
				    #"Typed columns"
