table Waterfall

	column waterfall_id
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: waterfall_id

	column account_id
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: account_id

	column month_start
		dataType: dateTime
		formatString: mmm yy
		isHidden
		summarizeBy: none
		sourceColumn: month_start

	column month_date_key
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: month_date_key

	column customer_sk
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: customer_sk

	column segment
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: segment

	column account_manager
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: account_manager

	column region
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: region

	column cohort_month
		dataType: dateTime
		formatString: Short Date
		isHidden
		summarizeBy: none
		sourceColumn: cohort_month

	column plan_id
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: plan_id

	column movement_category
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: movement_category

	column starting_mrr
		dataType: double
		formatString: #,0.00
		isHidden
		summarizeBy: none
		sourceColumn: starting_mrr

	column ending_mrr
		dataType: double
		formatString: #,0.00
		isHidden
		summarizeBy: none
		sourceColumn: ending_mrr

	column new_mrr
		dataType: double
		formatString: #,0.00
		isHidden
		summarizeBy: none
		sourceColumn: new_mrr

	column reactivation_mrr
		dataType: double
		formatString: #,0.00
		isHidden
		summarizeBy: none
		sourceColumn: reactivation_mrr

	column expansion_mrr
		dataType: double
		formatString: #,0.00
		isHidden
		summarizeBy: none
		sourceColumn: expansion_mrr

	column contraction_mrr
		dataType: double
		formatString: #,0.00
		isHidden
		summarizeBy: none
		sourceColumn: contraction_mrr

	column churned_mrr
		dataType: double
		formatString: #,0.00
		isHidden
		summarizeBy: none
		sourceColumn: churned_mrr

	partition Waterfall = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "mrr_waterfall_monthly.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    #"Typed columns" = Table.TransformColumnTypes(
				        #"Promoted headers",
				        {
						{"waterfall_id", type text},
						{"account_id", type text},
						{"month_start", type date},
						{"month_date_key", Int64.Type},
						{"customer_sk", Int64.Type},
						{"segment", type text},
						{"account_manager", type text},
						{"region", type text},
						{"cohort_month", type date},
						{"plan_id", type text},
						{"movement_category", type text},
						{"starting_mrr", type number},
						{"ending_mrr", type number},
						{"new_mrr", type number},
						{"reactivation_mrr", type number},
						{"expansion_mrr", type number},
						{"contraction_mrr", type number},
						{"churned_mrr", type number}
				        },
				        "en-US"
				    )
				in
				    #"Typed columns"
